EplangoTask/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EplangoTask.Core;
using EplangoTask.Core.DbEntities;
using EplangoTask.Persistence;
using EplangoTask.Persistence.ViewModels;

namespace EplangoTask.Controllers
{
    public class DepartmentController : Controller
    {
        private IUnitOfWork unitOfWork;
        public DepartmentController()
        {
            unitOfWork = new UnitOfWork();
        }

        public ActionResult List()
        {
            var department = unitOfWork.DepartmentRepository.GetAll(new string[0]);
            return View(department);
        }
        public ActionResult AddDepartment()
        {
            ViewBag.AvailableManagers = unitOfWork.EmployeeRepository.Find(x => x.Department == null, new string[0]).ToList();
            return View();
        }
        [HttpPost]
        public ActionResult AddDepartment(CreateDepartmentViewModel model)
        {
            if (ModelState.IsValid)
            {
                var department = new Department()
                {
                    Name = model.Name,
                    ManagerId = model.ManagerId ?? default(int)
                };
                unitOfWork.DepartmentRepository.Add(department);
                unitOfWork.Complete();
            }
            ViewBag.AvailableManagers = unitOfWork.EmployeeRepository.Find(x => x.Department == null, new string[0]).ToList();
            return View(model);
        }

        public ActionResult DepartmentDetails(int id)
        {
            var department = unitOfWork.DepartmentRepository.Find(x=>x.Id == id, new[] { "Employees", "Manager"}).FirstOrDefault();
            if (department == null)
                return View("Error");
            return View(department);
        }      
        [HttpPost]
        public ActionResult RemoveEmployee(int id)
        {
            var employee = unitOfWork.EmployeeRepository.Get(id, new[] { "Employees", "Manager"});
            if (employee == null)
                return View("Error");
            int deptid = employee.DepartmentId ?? default(int);
            employee.DepartmentId = null;
            unitOfWork.Complete();
            return RedirectToAction(nameof(DepartmentDetails),new{id= deptid});
        }
        public ActionResult ChangeManager(int id)
        {
            int currentManagerId = unitOfWork.DepartmentRepository.Get(id, new string[0]).Id;
            var managers = unitOfWork.EmployeeRepository.Find(x => x.DepartmentId == null && x.Id != currentManagerId,new string[0])
                .ToList();
            return PartialView("_PartialChangeManager",managers);
        }
        [HttpPost]
        public ActionResult ChangeManager(int managerId, int id)
        {
            var dept = unitOfWork.DepartmentRepository.Get(id, new string[0]);
            dept.ManagerId = managerId;
            unitOfWork.Complete();
            return RedirectToAction(nameof(DepartmentDetails), new { id = id });
        }
        public ActionResult AddEmployee(int id)
        {
            var idsList = unitOfWork.DepartmentRepository.GetAll(new string[0]).Select(x => x.ManagerId);
           
            var employees = unitOfWork.EmployeeRepository.Find(x => x.DepartmentId == null &&!idsList.Contains(x.Id) , new string[0])
                .ToList();
            return PartialView("_PartialAddEmployee", employees);
        }
        [HttpPost]
        public ActionResult AddEmployee(int empId, int id)
        {
            var emp = unitOfWork.EmployeeRepository.Get(empId,new string[0]);
            emp.DepartmentId = id;
            unitOfWork.Complete();

            return RedirectToAction(nameof(DepartmentDetails), new { id = id });
        }

        [HttpPost]
        public ActionResult DeleteDepartment(int id)
        {
            var dept = unitOfWork.DepartmentRepository.Get(id, new string[0]);
            if (dept != null)
            {
                var employees = unitOfWork.EmployeeRepository.Find(x => x.DepartmentId == id, new string[0]).ToList();
                foreach (var employee in employees)
                {
                    employee.DepartmentId = null;
                }
                unitOfWork.Complete();
                unitOfWork.DepartmentRepository.Delete(dept);
                unitOfWork.Complete();
            }

            return RedirectToAction(nameof(List));
        }
    }
}

EplangoTask/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EplangoTask.Core;
using EplangoTask.Core.DbEntities;
using EplangoTask.Persistence;
using EplangoTask.Persistence.ViewModels;

namespace EplangoTask.Controllers
{
    public class EmployeeController : Controller
    {
        private IUnitOfWork unitOfWork;
        public EmployeeController()
        {
            unitOfWork = new UnitOfWork();
        }


        public ActionResult AddEmployee()
        {
            ViewBag.Departments = unitOfWork.DepartmentRepository.GetAll( new string[0]).ToList();
            return View();
        }
        [HttpPost]
        public ActionResult AddEmployee(CreateEmployeeViewModel model)
        {
            if (ModelState.IsValid)
            {
                var employee = new Employee()
                {
                    Address = model.Address,
                    DepartmentId = model.DepartmentId ?? null,
                    Name = model.Name,
                    Phone = model.Phone
                };
                unitOfWork.EmployeeRepository.Add(employee);
                unitOfWork.Complete();

            }
            ViewBag.Departments = unitOfWork.DepartmentRepository.GetAll( new string[0]).ToList();
            return View(model);
        }
        //public ActionResult DeleteEmployee()
        //{
        //    return View();
        //}
        //public ActionResult UpdateEmployee()
        //{
        //    return View();
        //}
        //[HttpPost]
        //public ActionResult UpdateEmployee()
        //{
        //    return View();
        //}
    }
}

EplangoTask/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CrystalDecisions.CrystalReports.Engine;

namespace EplangoTask.Controllers
{
    public class ReportsController : Controller
    {
        // GET: Reports
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(int id)
        {
         

            ReportDocument rd = new ReportDocument();
            rd.Load(Path.Combine(Server.MapPath("~/Reporting"), MapSelectedReport(id)));
            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();
            rd.Refresh();

            rd.PrintOptions.PaperOrientation = CrystalDecisions.Shared.PaperOrientation.Landscape;
            rd.PrintOptions.ApplyPageMargins(new CrystalDecisions.Shared.PageMargins(5, 5, 5, 5));
            rd.PrintOptions.PaperSize = CrystalDecisions.Shared.PaperSize.PaperA5;

            Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
            stream.Seek(0, SeekOrigin.Begin);

            return File(stream, "application/pdf", "report.pdf");
        }

        private string MapSelectedReport(int id)
        {
            switch (id)
            {
                case 1:
                    return "ManagersDepartmentsReport.rpt";
                case 2:
                    return "DepartmentsReport.rpt";
                default:
                    return "ManagersDepartmentsReport.rpt";
            }
        }
    }
}

EplangoTask/Views/Department/AddDepartment.cshtml
@using EplangoTask.Core.DbEntities

@{
    ViewData["Title"] = "اضافة قسم جديد";
}

<!-- BEGIN: Content-->
<div class="app-content content">
    <div class="content-overlay"></div>
    <div class="content-wrapper">
        <div class="content-header row">
            <div class="content-header-left col-12 mb-2 mt-1">
                <div class="row breadcrumbs-top">
                    <div class="col-12">
                        <h5 class="content-header-title float-left pr-1 mb-0">اين انت :</h5>
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb p-0 mb-0">
                                <li class="breadcrumb-item">
                                    <a href=""><i class="bx bx-home-alt"></i></a>
                                </li>
                                <li class="breadcrumb-item">
                                    <a>ادارة الاقسام</a>
                                </li>
                                <li class="breadcrumb-item active">
                                    اضافة قسم جديد
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <!-- Description -->
            <section id="description" class="card">
                <div class="card-header">
                    <h4 class="card-title">
                    </h4>
                </div>
                <div class="card-content">
                    <div class="card-body">
                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane active" id="account-vertical-general" aria-labelledby="account-pill-general" aria-expanded="true">
         
                             
                              @using(Html.BeginForm("AddDepartment","Department",FormMethod.Post))
                              { 
                                    <div class="row">
                                        <div class="col-12">
                                           
                                            @Html.ValidationSummary()
                                        </div>
                                        <div class="col-12">
                                            <div class="form-group">
                                                <div class="controls">
                                                    <label name="Name">اسم القسم</label>
                                                    <input name="Name" class="form-control" placeholder="اسم القسم">
                                                </div>
                                            </div>
                                        </div>

                                        <div class="col-12">
                                            <div class="form-group">
                                                <div class="controls">
                                                    <label asp-for="ManagerId">المدير الخاص بالقسم</label>
                                                    <select name="ManagerId" class="form-control">
                                                        @foreach (var i in (List<Employee>)ViewBag.AvailableManagers)
                                                        {
                                                            <option value="@i.Id">@i.Name</option>
                                                        }
                                                    </select>
                                                </div>
                                            </div>
                                        </div>





                                        <div class="col-12 d-flex flex-sm-row flex-column justify-content-end">
                                            <button type="submit" class="btn btn-primary glow mr-sm-1 mb-1">
                                                اضافة القسم
                                            </button>
                                            <a href="/Department/List" class="btn btn-light mb-1">الغاء</a>
                                        </div>
                                    </div>
                              }
                            </div>

                        </div>





                    </div>
                </div>
            </section>
            <!--/ Description -->


        </div>
    </div>
</div>
<!-- END: Content-->
@section Scripts{


}

EplangoTask/Views/Department/DepartmentDetails.cshtml
@model EplangoTask.Core.DbEntities.Department
@{
    ViewBag.Title = "DepartmentDetails";
}

<!-- BEGIN: Content-->
<div class="app-content content">
    <div class="content-overlay"></div>
    <div class="content-wrapper">
        <div class="content-header row">
            <div class="content-header-left col-12 mb-2 mt-1">
                <div class="row breadcrumbs-top">
                    <div class="col-12">
                        <h5 class="content-header-title float-left pr-1 mb-0">اين انت :</h5>
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb p-0 mb-0">
                                <li class="breadcrumb-item">
                                    <a><i class="bx bx-home-alt"></i></a>
                                </li>
                                <li class="breadcrumb-item">
                                    <a>ادارة الاقسام</a>
                                </li>
                                <li class="breadcrumb-item active">
                                    قائمة الاقسام
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <!-- Description -->
            <section id="description" class="card">
                <div class="card-header">
                    <h4 class="card-title">
                        <b>اسم القسم : </b> @Model.Name
                    </h4>
                    <br />
                    <h4 class="card-title">
                        <b>اسم مدير القسم : </b> @Model.Manager.Name
                    </h4>
                    <br />
                    <div class="card-title">
                        @Ajax.ActionLink("تغيير مدير القسم", "ChangeManager", new { id = Model.Id }, new AjaxOptions() { InsertionMode = InsertionMode.Replace, HttpMethod = "Get", UpdateTargetId = "ChangeManagerDiv" }, new { @class = "btn btn-success", data_Toggle = "modal", data_Target = "#exampleModal" })
                    </div>
                    <br />
                    <div class="card-title">
                        @Ajax.ActionLink("اضافة موظف للقسم", "AddEmployee", new { id = Model.Id }, new AjaxOptions() { InsertionMode = InsertionMode.Replace, HttpMethod = "Get", UpdateTargetId = "AddEmployeeDiv" }, new { @class = "btn btn-primary", data_Toggle = "modal", data_Target = "#example1Modal" })
                    </div>
                </div>
                <div class="card-content">
                    <div class="card-body">
                        <table class="table table-striped" id="tbl">
                            <thead>
                                <tr>
                                    <th>اسم الموظف</th>
                                    <th>رقم الموظف</th>
                                    <th>عنوان الموظف</th>


                                    <th>العمليات المتاحة</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (!Model.Employees.Any())
                                {
                                    <tr>
                                        <td colspan="5">
                                            <h2 class="text-danger text-center">لا يوجد موظفين.</h2>
                                        </td>
                                    </tr>
                                }
                                @foreach (var employee in Model.Employees)
                                {
                                    <tr>
                                        <td>@employee.Name</td>
                                        <td>@employee.Phone</td>
                                        <td>@employee.Address</td>


                                        <td>
                                            <div class="row">

                                                <div class="col-md-12">
                                                    @using (Html.BeginForm("RemoveEmployee", "Department", new { id = employee.Id }, FormMethod.Post, new { @class = "deleteForm" }))
                                                    {
                                                        <button class="btn btn-danger" type="submit">حذف من القسم</button>
                                                    }
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                }

                            </tbody>
                        </table>
                    </div>
                </div>
            </section>
            <!--/ Description -->


        </div>
    </div>
</div>
<!-- END: Content-->
@section Scripts
{
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js" type="text/javascript"></script>

    <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js" type="text/javascript"></script>



    <script src="~/Content/bootbox.js/bootbox.js"></script>
    <script>
        $('#tbl').DataTable({
            //paging: false,
            "language": {
                "sProcessing": "جارٍ التحميل...",
                "sLengthMenu": "أظهر _MENU_ مدخلات",
                "sZeroRecords": "لم يعثر على أية سجلات",
                "sInfo": "إظهار _START_ إلى _END_ من أصل _TOTAL_ مدخل",
                "sInfoEmpty": "يعرض 0 إلى 0 من أصل 0 سجل",
                "sInfoFiltered": "(منتقاة من مجموع _MAX_ مُدخل)",
                "sInfoPostFix": "",
                "sSearch": "ابحث:",
                "sUrl": "",
                "oPaginate": {
                    "sFirst": "الأول",
                    "sPrevious": "السابق",
                    "sNext": "التالي",
                    "sLast": "الأخير"
                }
            }
        });

        $('.deleteForm').click(function (e) {
            let event = e;
            e.preventDefault();
            bootbox.confirm({
                message: "هل انت متاكد من عمليه الحذف ؟",
                buttons: {
                    confirm: {
                        label: 'نعم ',
                        className: 'btn-success'
                    },
                    cancel: {
                        label: 'لا ',
                        className: 'btn-danger'
                    }
                },
                callback: function (result) {
                    if (result) {
                        console.log(e.target);
                        e.target.parentNode.submit();
                    }
                }
            });

        });



    </script>
}

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">تغيير المدير</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="ChangeManagerDiv"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">اغلاق</button>

            </div>
        </div>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="example1Modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">اضافة موظف للقسم</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="AddEmployeeDiv"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">اغلاق</button>

            </div>
        </div>
    </div>
</div>

EplangoTask/Views/Department/List.cshtml
@using System.Collections.Specialized
@model IEnumerable<EplangoTask.Core.DbEntities.Department>
@{
    ViewData["Title"] = "قائمة الاقسام";
}

<!-- BEGIN: Content-->
<div class="app-content content">
    <div class="content-overlay"></div>
    <div class="content-wrapper">
        <div class="content-header row">
            <div class="content-header-left col-12 mb-2 mt-1">
                <div class="row breadcrumbs-top">
                    <div class="col-12">
                        <h5 class="content-header-title float-left pr-1 mb-0">اين انت :</h5>
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb p-0 mb-0">
                                <li class="breadcrumb-item">
                                    <a><i class="bx bx-home-alt"></i></a>
                                </li>
                                <li class="breadcrumb-item">
                                    <a>ادارة الاقسام</a>
                                </li>
                                <li class="breadcrumb-item active">
                                    قائمة الاقسام
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <!-- Description -->
            <section id="description" class="card">
                <div class="card-header">
                    <h4 class="card-title">
                        <a href="/Department/AddDepartment" class="btn btn-primary btn-lg btn-link">
                            اضافة قسم جديد
                        </a>
                    </h4>
                </div>
                <div class="card-content">
                    <div class="card-body">
                        <table class="table table-striped" id="tbl">
                            <thead>
                                <tr>
                                    <th>اسم القسم</th>


                                    <th>العمليات المتاحة</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (!Model.Any())
                                {
                                    <tr>
                                        <td colspan="5">
                                            <h2 class="text-danger text-center">لا يوجد اقسام.</h2>
                                        </td>
                                    </tr>
                                }
                                @foreach (var department in Model)
                                {
                                    <tr>
                                        <td>@department.Name</td>


                                        <td>
                                            <div class="row">
                                                <div class="col-md-4">
                                                    @Html.ActionLink("تفاصيل القسم", "DepartmentDetails", new { id = department.Id }, new { @class = "btn btn-info" })
                                                </div>
                                                <div class="col-md-4">
                                                    @using (Html.BeginForm("DeleteDepartment", "Department", new { id = department.Id }, FormMethod.Post, new { @class = "deleteForm" }))
                                                    {
                                                        <button type="submit" class="btn btn-danger">حذف القسم</button>
                                                    }
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                }

                            </tbody>
                        </table>
                    </div>
                </div>
            </section>
            <!--/ Description -->


        </div>
    </div>
</div>
<!-- END: Content-->
@section Scripts
{
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js" type="text/javascript"></script>

    <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js" type="text/javascript"></script>
    <script src="~/Content/bootbox.js/bootbox.min.js"></script>


    <script>
        $('#tbl').DataTable({
            //paging: false,
            "language": {
                "sProcessing": "جارٍ التحميل...",
                "sLengthMenu": "أظهر _MENU_ مدخلات",
                "sZeroRecords": "لم يعثر على أية سجلات",
                "sInfo": "إظهار _START_ إلى _END_ من أصل _TOTAL_ مدخل",
                "sInfoEmpty": "يعرض 0 إلى 0 من أصل 0 سجل",
                "sInfoFiltered": "(منتقاة من مجموع _MAX_ مُدخل)",
                "sInfoPostFix": "",
                "sSearch": "ابحث:",
                "sUrl": "",
                "oPaginate": {
                    "sFirst": "الأول",
                    "sPrevious": "السابق",
                    "sNext": "التالي",
                    "sLast": "الأخير"
                }
            }
        });

        $('.deleteForm').click(function (e) {
            let event = e;
            e.preventDefault();
            bootbox.confirm({
                message: "هل انت متاكد من عمليه الحذف ؟",
                buttons: {
                    confirm: {
                        label: 'نعم ',
                        className: 'btn-success'
                    },
                    cancel: {
                        label: 'لا ',
                        className: 'btn-danger'
                    }
                },
                callback: function (result) {
                    if (result) {
                        console.log(e.target);
                        e.target.parentNode.submit();
                    }
                }
            });

        });



    </script>
}

EplangoTask/Views/Reports/Index.cshtml
@{
    ViewData["Title"] = "قائمة التقارير";
}

<!-- BEGIN: Content-->
<div class="app-content content">
    <div class="content-overlay"></div>
    <div class="content-wrapper">
        <div class="content-header row">
            <div class="content-header-left col-12 mb-2 mt-1">
                <div class="row breadcrumbs-top">
                    <div class="col-12">
                        <h5 class="content-header-title float-left pr-1 mb-0">اين انت :</h5>
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb p-0 mb-0">
                                <li class="breadcrumb-item">
                                    <a><i class="bx bx-home-alt"></i></a>
                                </li>
                                <li class="breadcrumb-item">
                                    <a>ادارة التقارير</a>
                                </li>
                                <li class="breadcrumb-item active">
                                    قائمة التقارير
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <!-- Description -->
            <section id="description" class="card">
          
                <div class="card-content">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-4">
                                @using (Html.BeginForm("Index","Reports",new { id = 1},FormMethod.Post))
                                {
                                    <button class="btn btn-primary" type="submit">جميع الاقسام مع المدراء</button>
                                }
                            </div>
                            <div class="col-md-4">
                                @using (Html.BeginForm("Index","Reports",new { id = 2},FormMethod.Post))
                                {
                                    <button class="btn btn-primary" type="submit">جميع الاقسام مع الموظفين</button>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!--/ Description -->


        </div>
    </div>
</div>

EplangoTask/Views/Shared/_PartialAddEmployee.cshtml
@using EplangoTask.Core.DbEntities
@model IEnumerable<EplangoTask.Core.DbEntities.Employee>
@using (Html.BeginForm("AddEmployee","Department",FormMethod.Post,new{}))
{


    <div class="col-12">
        <div class="form-group">
            <div class="controls">
                @Html.Hidden("id", Url.RouteCollection["id"])
                <label asp-for="empId">الموظفين المتاحين للاضافة</label>
                <select name="empId" class="form-control">
                    @foreach (var i in Model)
                    {
                        <option value="@i.Id">@i.Name</option>
                    }
                </select>
            </div>
        </div>
        <button class="btn btn-success" type="submit">اضافة الموظف</button>
    </div>
}

EplangoTask/Views/Shared/_PartialChangeManager.cshtml
@using EplangoTask.Core.DbEntities
@model IEnumerable<EplangoTask.Core.DbEntities.Employee>
   @using (Html.BeginForm("ChangeManager","Department",FormMethod.Post,new{}))
   {


       <div class="col-12">
           <div class="form-group">
               <div class="controls">
                   @Html.Hidden("id", Url.RouteCollection["id"])
                   <label asp-for="managerId">المدير الخاص بالقسم</label>
                   <select name="managerId" class="form-control">
                       @foreach (var i in Model)
                       {
                           <option value="@i.Id">@i.Name</option>
                       }
                   </select>
               </div>
           </div>
           <button class="btn btn-success" type="submit">تعديل المدير</button>
       </div>
   }